name: Workflow Dispatch Freeform Input Example

on:
  workflow_dispatch:
    inputs:
      environment: # this represent an environment that we'll deploy to, normally
        description: 'The environment to deploy to'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }} environment!"
